name: Deploy Site Ctech

on:
  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > SITE_CTECH && chmod 600 SITE_CTECH
          ssh -o StrictHostKeyChecking=no -i SITE_CTECH ${USER_NAME}@${HOSTNAME} '

              cd /ctech/site-ctech/front
              git pull
              npm install --production
              npm run build
              pm2 restart site-ctech
              '
